language: cpp
compiler: gcc
os: linux
dist: trusty
sudo: required


before_install:
  - sudo apt-get update -qq


install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8

  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

  - sudo apt-get install -y libboost1.55-dev
  - sudo apt-get install -y libboost-regex1.55-dev
  - sudo apt-get install -y libboost-system1.55-dev
  - sudo apt-get install -y libboost-thread1.55-dev
  - sudo apt-get install -y libboost-program-options1.55-dev
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y python-all-dev
  - sudo apt-get install -y swig
  - sudo apt-get install -y liboce-foundation-dev
  - sudo apt-get install -y liboce-modeling-dev
  - sudo apt-get install -y liboce-ocaf-dev
  - sudo apt-get install -y liboce-visualization-dev
  - sudo apt-get install -y liboce-ocaf-lite-dev

  - sudo apt-get install -y libpcre3-dev

script:
# test nix/build-all.py script (before the build following build instructions in order to no mess up installations into /usr/local)
  - cd nix
  - python build-all.py
  - cd ..
# test build according to build instructions
  - pwd
  - cd ..
  - git clone https://github.com/KhronosGroup/OpenCOLLADA.git
  - cd OpenCOLLADA
  - git checkout 064a60b65c2c31b94f013820856bc84fb1937cc6
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..
  - pwd
  - cd IfcOpenShell
  - pwd
  - cd cmake
  - mkdir build
  - cd build
  - cmake -DCOLLADA_SUPPORT=True -DOPENCOLLADA_INCLUDE_DIR=/usr/local/include/opencollada -DOPENCOLLADA_LIBRARY_DIR=/usr/local/lib/opencollada -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu -DUSE_IFC4=False -DBUILD_IFCPYTHON=True -DUNICODE_SUPPORT=True -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu  ..
  - make -j2
  - pwd
  - cd ..
  - cd ..

after_failure:
  - cat build/Linux/x86_64/logs/*.log
