language: cpp
compiler: gcc
os: linux
dist: trusty
sudo: required


before_install:
  - sudo apt-get update -qq


install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8

  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

  - sudo apt-get install -y libboost1.55-dev
  - sudo apt-get install -y libboost-regex1.55-dev
  - sudo apt-get install -y libboost-system1.55-dev
  - sudo apt-get install -y libboost-thread1.55-dev
  - sudo apt-get install -y libboost-program-options1.55-dev
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y python-all-dev
  - sudo apt-get install -y swig
  - sudo apt-get install -y liboce-foundation-dev
  - sudo apt-get install -y liboce-modeling-dev
  - sudo apt-get install -y liboce-ocaf-dev
  - sudo apt-get install -y liboce-visualization-dev
  - sudo apt-get install -y liboce-ocaf-lite-dev


script:
  - cd cmake
  - mkdir build
  - cd build
  - cmake -DCOLLADA_SUPPORT=False -DUSE_IFC4=False -DBUILD_IFCPYTHON=True -DUNICODE_SUPPORT=True  ..
  - make -j2
