schema_version = "1.0.0"
id = "blenderbim"
version = "0.0.999999"
name = "BlenderBIM"
tagline = "Transforms Blender into a native Building Information Model authoring platform using IFC."
maintainer = "Dion Moult <dion@thinkmoult.com>"
type = "add-on"
permissions = ["files"]
website = "https://blenderbim.org/"
tags = ["System"]
blender_version_min = "3.5.0"
license = ["SPDX:GPL-3.0-or-later"]
