name: Publish-blenderbim-multiplatform

on:
  push:
    paths:
      - 'src/ifcblenderexport/*'
      - '.github/workflows/ci-blenderbim-matrix.yml'

env:
  major: 0
  minor: 0
  name: blenderbim

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell' &&
      contains(github.event.head_commit.message, '[Release]')
    steps:
    - name: Set env
      run: echo ok go

  build:
    name: ${{ matrix.config.name }}-${{ matrix.pyver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: [py37, py39]
        config:
          - {
            name: "Windows Build",
            short_name: win,
          }
          - {
            name: "Linux Build",
            short_name: linux
          }
          - {
            name: "MacOS Build",
            short_name: macos
          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          python-version: '3.7.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: echo ${{ env.DATE }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Compile
        run: |
          cp -r src/ifcblenderexport src/ifcblenderexport_${{ matrix.config.short_name }}_${{ matrix.pyver }} &&
          cd src/ifcblenderexport_${{ matrix.config.short_name }}_${{ matrix.pyver }} &&
          make dist PLATFORM=${{ matrix.config.short_name }} PYVERSION=${{ matrix.pyver }}
      - name: Upload Zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/ifcblenderexport_${{ matrix.config.short_name }}_${{ matrix.pyver }}/dist/blender28-bim-${{steps.date.outputs.date}}-${{ matrix.pyver }}-${{ matrix.config.short_name }}.zip
          asset_name: blender28-bim-${{steps.date.outputs.date}}-${{ matrix.pyver }}-${{ matrix.config.short_name }}.zip
          tag: "blenderbim-${{steps.date.outputs.date}}"
          overwrite: true
          body: "Package release blenderbim-${{steps.date.outputs.date}}"
