name: ci-ifcopenshell-python

on:
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
    - name: Set env
      run: echo ok go

  build:
    needs: activate
    name: ${{ matrix.config.name }}-${{ matrix.pyver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: [py39, py310, py311, py312]
        config:
          - {
            name: "Windows Build",
            short_name: win64,
          }
          - {
            name: "Linux Build",
            short_name: linux64
          }
          - {
            name: "MacOS Build",
            short_name: macos64
          }
          - {
            name: "MacOS ARM Build",
            short_name: macosm164
          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: echo ${{ env.DATE }}
      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(cat ../../VERSION)"
      - name: Compile
        run: |
          cp -r src/ifcopenshell-python src/ifcopenshell_${{ matrix.config.short_name }}_${{ matrix.pyver }} &&
          cd src/ifcopenshell_${{ matrix.config.short_name }}_${{ matrix.pyver }} &&
          make zip PLATFORM=${{ matrix.config.short_name }} PYVERSION=${{ matrix.pyver }}
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/ifcopenshell_${{ matrix.config.short_name }}_${{ matrix.pyver }}/dist/ifcopenshell-python-${{ steps.version.outputs.version }}-${{ matrix.pyver }}-${{ matrix.config.short_name }}.zip
          asset_name: ifcopenshell-python-${{ steps.version.outputs.version }}-${{ matrix.pyver }}-${{ matrix.config.short_name }}.zip
          overwrite: true
          body: "IfcOpenShell-Python Build ifcopenshell-python-${{steps.version.outputs.version}}"
